/**
 * Created by 周鹏斌大王 on 2018-04-15.
 */
class Zpb_test_model_1{

    public static fields_analysis={
        a:"user",
        b:"users"
    }

    public  static mainInfo=
        {
            "currentUser": {
                "userId": "666666",
                "position": 2,
                "score": 100,
                "state": 1,
                "playStatus": 2,
                "hasPuFen": -1,
                "userName": "伟大的周鹏斌大王",
                "userImg": "http://www.aoh5.com:8086/h5/AH/site/img/head/zhoudw.png",
                "gender": 1,
                "ip": "192.168.1.123",
                "userAgree": "用户是否同意",
                "money": "用户当前余额",
                "notice": "系统公告(跑马灯)",
                "lastAction": [],
                "currAction": [],
                "pais": [
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14
                ],
                "chuList": [
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23,
                    24,
                    25,
                    26,
                    27,
                    28,
                    29,
                    30,
                    31,
                    32,
                    33,
                    34,
                    1,
                    2
                ],
                "actionList": []
            },
            "roomInfo": {
                "userId": "666666",
                "userName": "伟大的周鹏斌大王",
                "roomId": 888888,
                "state": 3,
                "lastNum": 1,
                "circleNum": 2,
                "currMJNum": 66,
                "roomType": 1,
                "scoreType": 1,
                "ruleJueGang": "",
                "ruleXuanFeng": "",
                "ruleChangMao": "",
                "ruleTuiDaoHu": "",
                "ruleDaiHun": "",
                "ruleQiongHu": "",
                "ruleQingYiSe": "",
                "ruleQiDui": "",
                "rulePuFen": "",
                "playType": "经典/盖州",
                "hunPai": 6,
                "zhuangPlayer": "777777",
                "xjst": "小局开始时间",
                "lastAction": -1,
                "lastActionUserId": "666666"
            },
            "anotherUsers": [
                {
                    "userId": "777777",
                    "position": 1,
                    "score": 0,
                    "money": 0,
                    "hasPuFen": -1,
                    "playStatus": 3,
                    "userName": "周周周小弟",
                    "userImg": "http://www.aoh5.com:8086/h5/AH/site/img/head/wsw_zc.png",
                    "ip": "192.168.1.123",
                    "joinIndex": "进入房间的顺序",
                    "pais": 14,
                    "chuList": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26,
                        27,
                        28,
                        29,
                        30,
                        31,
                        32,
                        33,
                        34,
                        1,
                        2
                    ]
                },
                {
                    "userId": "55555",
                    "position": 3,
                    "score": 0,
                    "hasPuFen": -1,
                    "money": 0,
                    "playStatus": 3,
                    "userName": "美女美女",
                    "userImg": "http://www.aoh5.com:8086/h5/AH/site/img/head/wsw_hl.png",
                    "ip": "192.168.1.6",
                    "joinIndex": "进入房间的顺序",
                    "pais": 14,
                    "chuList": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26,
                        27,
                        28,
                        29,
                        30,
                        31,
                        32,
                        33,
                        34,
                        1,
                        2
                    ]
                },
                {
                    "userId": "33333",
                    "position": 4,
                    "score": 0,
                    "hasPuFen": 1,
                    "money": 0,
                    "playStatus": 3,
                    "userName": "小黄人",
                    "userImg": "http://www.aoh5.com:8086/h5/AH/site/img/head/wsw_tyq.png",
                    "ip": "192.168.1.6",
                    "joinIndex": "进入房间的顺序",
                    "pais": 14,
                    "chuList": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26,
                        27,
                        28,
                        29,
                        30,
                        31,
                        32,
                        33,
                        34,
                        1,
                        2
                    ]
                }
            ]
        }

}