/**
 * Created by zwb on 2018/4/18.
 */
class Zwb_test_model_1{

    public static fields_analysis={

        a:"user",
        b:"users"


    };
    public  static mainInfo={
        currentUser:{
            "userId":"",
            "position":"风向",
            "score":"总分数",
            "state":"在线/离线状态 1/0",
            "playStatus":1,//玩家游戏状态",//1大厅 2未准备 3准备 4游戏中
            "hasPuFen":"",//0（否）或者1（是）  ，没选铺分的话不会给这个字段
            "userName":"微信昵称",
            "userImg":"微信头像",
            "gender":"性别",
            "ip":"",
            "userAgree":"用户是否同意",
            "money":"用户当前余额",
            "notice":"系统公告(跑马灯)",
            "lastAction":[],//上个动作列表
            "currAction":[],//当前动作列表
            "pais":"[]",//不排序
            "chuList":"[]",//出过的牌
            "actionList":[]// 吃碰杠
        }
    }

    //获取我的俱乐部(主页)
    public static get_my_club_list=[
            {
                "clubId":"俱乐部1",
                "clubName":"俱乐部1",
                "clubUserName":"创建人",
                "allNums":"41",
                "freeStart":"限免开始时间",
                "freeEnd":"限免结束时间"
            },
            {
                "clubId":"俱乐部2",
                "clubName":"俱乐部2",
                "clubUserName":"创建人",
                "allNums":"42",
                "freeStart":"限免开始时间",
                "freeEnd":"限免结束时间"
            },
            {
                "clubId":"俱乐部3",
                "clubName":"俱乐部3",
                "clubUserName":"创建人",
                "allNums":"43",
                "freeStart":"限免开始时间",
                "freeEnd":"限免结束时间"
            },
            {
                "clubId":"俱乐部4",
                "clubName":"俱乐部4",
                "clubUserName":"创建人",
                "allNums":"44",
                "freeStart":"限免开始时间",
                "freeEnd":"限免结束时间"
            },
            {
                "clubId":"俱乐部5",
                "clubName":"俱乐部5",
                "clubUserName":"创建人",
                "allNums":"45",
                "freeStart":"限免开始时间",
                "freeEnd":"限免结束时间"
            },
            {
                "clubId":"俱乐部6",
                "clubName":"俱乐部6",
                "clubUserName":"创建人",
                "allNums":"46",
                "freeStart":"限免开始时间",
                "freeEnd":"限免结束时间"
            }
        ];

    //获取某个俱乐部详情(广场)
    public static get_club_info=[
        {
                "clubId":"1000111",
                "clubUserName":"周鹏斌大王",
                "clubMoney":"1000",
                "cardQuota":"100",
                "used":"100",
                "juNum":"100",
                "actNum":"1000",
                clubName:"阿瓦隆俱乐部",
                createTimer:"2016-09-09",
                peopernum:10,
                "freeStart":"限免开始时间",
                "freeEnd":"限免结束时间",
                "rooms":[{//这个列表都是默认未开局的
                    "rId":"10001",
                    "userName":"创建人昵称",
                    "userImg":"创建人头像",
                    "num":"当前人数",
                    "circleNum":"10",
                    "mingPaiType":"当前人数",
                    "diZhuType":"当前人数",
                    "can4Take2":"当前人数",
                    "mulType":"当前人数",
                    "dingFen":"当前人数",
                    "daPaiJiaoMan":"当前人数",
                    "roomType":1,
                    "laiZi":"当前人数",
                    "rule":"规则，详见说明",
                    user_list:[
                        {
                            headImg:"http://www.qqzhi.com/uploadpic/2014-09-23/000247589.jpg",
                            userName:"周鹏斌大王"
                        }
                    ]
                },{//这个列表都是默认未开局的
                    "rId":"10001",
                    "userName":"创建人昵称",
                    "userImg":"创建人头像",
                    "num":"当前人数",
                    "circleNum":"10",
                    "mingPaiType":"当前人数",
                    "diZhuType":"当前人数",
                    "can4Take2":"当前人数",
                    "mulType":"当前人数",
                    "dingFen":"当前人数",
                    "daPaiJiaoMan":"当前人数",
                    "roomType":1,
                    "laiZi":"当前人数",
                    "rule":"规则，详见说明",
                    user_list:[
                        {
                            headImg:"http://www.qqzhi.com/uploadpic/2014-09-23/000247589.jpg",
                            userName:"周鹏斌大王"
                        }
                    ]
                },{//这个列表都是默认未开局的
                    "rId":"10001",
                    "userName":"创建人昵称",
                    "userImg":"创建人头像",
                    "num":"当前人数",
                    "circleNum":"10",
                    "mingPaiType":"当前人数",
                    "diZhuType":"当前人数",
                    "can4Take2":"当前人数",
                    "mulType":"当前人数",
                    "dingFen":"当前人数",
                    "daPaiJiaoMan":"当前人数",
                    "roomType":1,
                    "laiZi":"当前人数",
                    "rule":"规则，详见说明",
                    user_list:[
                        {
                            headImg:"http://www.qqzhi.com/uploadpic/2014-09-23/000247589.jpg",
                            userName:"周鹏斌大王"
                        }
                    ]
                },{//这个列表都是默认未开局的
                    "rId":"10001",
                    "userName":"创建人昵称",
                    "userImg":"创建人头像",
                    "num":"当前人数",
                    "circleNum":"10",
                    "mingPaiType":"当前人数",
                    "diZhuType":"当前人数",
                    "can4Take2":"当前人数",
                    "mulType":"当前人数",
                    "dingFen":"当前人数",
                    "daPaiJiaoMan":"当前人数",
                    "roomType":1,
                    "laiZi":"当前人数",
                    "rule":"规则，详见说明",
                    user_list:[
                        {
                            headImg:"http://www.qqzhi.com/uploadpic/2014-09-23/000247589.jpg",
                            userName:"周鹏斌大王"
                        }
                    ]
                },{//这个列表都是默认未开局的
                    "rId":"10001",
                    "userName":"创建人昵称",
                    "userImg":"创建人头像",
                    "num":"当前人数",
                    "circleNum":"10",
                    "mingPaiType":"当前人数",
                    "diZhuType":"当前人数",
                    "can4Take2":"当前人数",
                    "mulType":"当前人数",
                    "dingFen":"当前人数",
                    "daPaiJiaoMan":"当前人数",
                    "roomType":1,
                    "laiZi":"当前人数",
                    "rule":"规则，详见说明",
                    user_list:[
                        {
                            headImg:"http://www.qqzhi.com/uploadpic/2014-09-23/000247589.jpg",
                            userName:"周鹏斌大王"
                        }
                    ]
                }]
        }
    ];

    //俱乐部-我的成绩
    public static get_club_get_my_info=
        {
            "juNum": 100,"score":1000,"pages":2,"page":1,
            "infos":[
                    {
                        "rId":"123456",
                        "ct":"创建时间long类型的",
                        "users":[
                            {
                                "userId":1111,
                                "userName":"擦擦啊啊啊啊",
                                "finalScore":123,
                                "time":1334556666
                            },
                            {
                                "userId":1111,
                                "userName":"擦擦啊啊啊啊",
                                "finalScore":123,
                                "time":1334556666
                            },
                            {
                                "userId":1111,
                                "userName":"擦擦啊啊啊啊",
                                "finalScore":-123,
                                "time":1334556666
                            }
                        ]
                    },
                    {
                        "rId":"123456",
                        "ct":"创建时间long类型的",
                        "users":[
                            {
                                "userId":1111,
                                "userName":"擦擦啊啊啊啊",
                                "finalScore":123,
                                "time":1334556666
                            },
                            {
                                "userId":1111,
                                "userName":"擦擦啊啊啊啊",
                                "finalScore":123,
                                "time":1334556666
                            },
                            {
                                "userId":1111,
                                "userName":"擦擦啊啊啊啊",
                                "finalScore":-123,
                                "time":1334556666
                            }
                        ]
                    },
                    {
                        "rId":"123456",
                        "ct":"创建时间long类型的",
                        "users":[
                            {
                                "userId":1111,
                                "userName":"擦擦啊啊啊啊",
                                "finalScore":123,
                                "time":1334556666
                            },
                            {
                                "userId":1111,
                                "userName":"擦擦啊啊啊啊",
                                "finalScore":123,
                                "time":1334556666
                            },
                            {
                                "userId":1111,
                                "userName":"擦擦啊啊啊啊",
                                "finalScore":-123,
                                "time":1334556666
                            }
                        ]
                    },
                    {
                        "rId":"123456",
                        "ct":"创建时间long类型的",
                        "users":[
                            {
                                "userId":1111,
                                "userName":"擦擦啊啊啊啊",
                                "finalScore":123,
                                "time":1334556666
                            },
                            {
                                "userId":1111,
                                "userName":"擦擦啊啊啊啊",
                                "finalScore":123,
                                "time":1334556666
                            },
                            {
                                "userId":1111,
                                "userName":"擦擦啊啊啊啊",
                                "finalScore":-123,
                                "time":1334556666
                            }
                        ]
                    },
                    {
                        "rId":"123456",
                        "ct":"创建时间long类型的",
                        "users":[
                            {
                                "userId":1111,
                                "userName":"擦擦啊啊啊啊",
                                "finalScore":123,
                                "time":1334556666
                            },
                            {
                                "userId":1111,
                                "userName":"擦擦啊啊啊啊",
                                "finalScore":123,
                                "time":1334556666
                            },
                            {
                                "userId":1111,
                                "userName":"擦擦啊啊啊啊",
                                "finalScore":-123,
                                "time":1334556666
                            }
                        ]
                    }
                  ]
        }







}